name: PR Test

on:
  pull_request:
    branches:
      - stg
      - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo message
        run: echo "Running test for the Pull Request"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Build For Fun
        run: npm run build --if-present
        